### ISSUE TITLE
Collection with no paths (ERROR)

### ISSUE THREAD

**Issue by dsvanidze** [vatson/rollup-plugin-vuetify#5]
Hi,

your npm package does not work with rollup. 

```bash
[!] (plugin at position 9) Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
src/components/Collection/FormElements/InputText.vue?rollup-plugin-vue=script.ts
Error: You cannot call "get" on a collection with no paths. Instead, check the "length" property first to verify at least 1 path exists.
```

The error is caused by this line of code https://github.com/vatson/rollup-plugin-vuetify/blob/master/src/transform.js#L83.

Do you have an idea how can I fix it?

**Comment by vatson** [comment]
Hey @dsvanidze.

It looks like another use case that I did not predict.

I can not reproduce this error. Could you provide the source of your `src/components/Collection/FormElements/InputText.vue` or an example based on it?

**Comment by vatson** [comment]
@dsvanidze 

I got it. 

You don't define the default export or even `<script>` section in that component. Right? Honestly, I have not considered this use case. I'll add handling of this. 

Please let me know if this is a different use case.

**Comment by dsvanidze** [comment]
@vatson Thank you very much for you response. 

Yes problem was `export default {}` definition. I used a code like this, because I need it.
```
const x = Vue.extend({...})
export default x
```

I changed the pattern to 
```
export default Vue.extend({...})
```
and it works. However, it would be great if your plugin could detect patterns like this.

Now it only shows a warning:
`(!) Broken sourcemap
https://rollupjs.org/guide/en/#warning-sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as 'at position 9') should generate accompanying sourcemaps`.


I also see many other errors in the Dev Console of the browser.
![Bildschirmfoto 2020-06-01 um 18 43 27](https://user-images.githubusercontent.com/14854973/83431691-08252f80-a438-11ea-90cf-313e2ff7f03f.png)

**Comment by vatson** [comment]
@dsvanidze 

Yeah, your case is another case that I just discovered when I was trying to fix a problem of transforming sfc component without `script` section (I supposed before).

I plan to add support for your case/pattern too.

Regarding your errors. I have never encountered sourcemap and RTL errors. I will take a look, but  in a scope of the next separate issues.

Thank you for your feedback and contribution. Feel free to open the other issues with with additional details how to reproduce the errors.

**Comment by dsvanidze** [comment]
Great! Thanks a lot!
