### ISSUE TITLE
Error trying demo

### ISSUE THREAD

**Issue by dalopezarco** [vatson/rollup-plugin-vuetify#50]
Hello, I just downloaded the repo and try to run the demo but I get the next output: 

"C:\Program Files\nodejs\node.exe" C:\Repos\Personal\rollup-plugin-vuetify-dev\demo\rollup.js
(node:22516) UnhandledPromiseRejectionWarning: Error: @rollup/plugin-typescript: Could not find C:/Repos/Personal/rollup-plugin-vuetify-dev/demo/src/Components/Extended.vue?rollup-plugin-vue=script.ts
    at getFile (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\@rollup\plugin-typescript\dist\index.js:130:23)
    at Object.getScriptVersion (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\@rollup\plugin-typescript\dist\index.js:158:41)
    at C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\typescript\lib\typescript.js:139206:136
    at sourceFileVersionUptoDate (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\typescript\lib\typescript.js:99956:43)
    at sourceFileNotUptoDate (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\typescript\lib\typescript.js:99952:21)
    at Array.some (<anonymous>)
    at Object.isProgramUptoDate (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\typescript\lib\typescript.js:99933:38)
    at synchronizeHostData (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\typescript\lib\typescript.js:139206:20)
    at Object.getProgram (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\typescript\lib\typescript.js:139368:13)
    at Object.generateBundle (C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\@rollup\plugin-typescript\dist\index.js:471:38)
    at C:\Repos\Personal\rollup-plugin-vuetify-dev\node_modules\rollup\dist\shared\rollup.js:18233:25
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:22516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Circular dependency: ..\node_modules\vuetify\lib\util\console.js -> ..\node_modules\vuetify\lib\framework.js -> ..\node_modules\vuetify\lib\install.js -> ..\node_modules\vuetify\lib\util\console.js
Circular dependency: ..\node_modules\vuetify\lib\util\console.js -> ..\node_modules\vuetify\lib\framework.js -> ..\node_modules\vuetify\lib\services\index.js -> ..\node_modules\vuetify\lib\services\lang\index.js -> ..\node_modules\vuetify\lib\util\console.js
Circular dependency: ..\node_modules\vuetify\lib\util\console.js -> ..\node_modules\vuetify\lib\framework.js -> ..\node_modules\vuetify\lib\services\index.js -> ..\node_modules\vuetify\lib\services\presets\index.js -> ..\node_modules\vuetify\lib\util\console.js
Circular dependency: ..\node_modules\vuetify\lib\util\console.js -> ..\node_modules\vuetify\lib\framework.js -> ..\node_modules\vuetify\lib\services\index.js -> ..\node_modules\vuetify\lib\services\theme\index.js -> ..\node_modules\vuetify\lib\services\theme\utils.js -> ..\node_modules\vuetify\lib\util\colorUtils.js -> ..\node_modules\vuetify\lib\util\console.js

**Comment by vatson** [comment]
Hello @dalopezarco,

Sorry for the delay with response. I've just caught a time to check it with Windows. You are absolutely right, the build is broken. But it's an issue of `@rollup/plugin-typescript` compatibility with Windows. 

Current demo is built on top of `@rollup/plugin-typescript` at **3.1.1**. This is last version supported by `rollup-plugin-vuetify`. The next `@rollup/plugin-typescript` versions switched from **_LanguageService_** to **_BuilderProgram_** (https://github.com/rollup/plugins/pull/217) which didn't support vue. This did not work with version 4.0.0 for sure, but I plan to check those coming after 4.0.0, maybe something has improved.


If you still want to test the plugin, you just need to comment out the following lines https://github.com/vatson/rollup-plugin-vuetify/blob/dev/demo/rollup.js#L18-L35 and restart build.

I will close the issue for now.  If you have something, write here or open a new one
